import { observable } from '@legendapp/state'

import type {
  Bucket,
  CommentItem,
  DiffFile,
  DiffStyle,
  FileItem,
  GitSnapshot,
  HistoryNavTarget,
  HistoryCommit,
  RunningAction,
  ViewMode,
} from './types'

export const appState$ = observable({
  repos: [] as string[],
  activeRepo: '',
  viewMode: 'changes' as ViewMode,
  snapshot: null as GitSnapshot | null,
  historyCommits: [] as HistoryCommit[],
  historyFilter: '',
  historyCommitId: '',
  historyNavTarget: 'commits' as HistoryNavTarget,
  historyFiles: [] as FileItem[],
  collapseStaged: false,
  collapseUnstaged: false,
  activeBucket: 'unstaged' as Bucket,
  activePath: '',
  patch: '',
  oldFile: null as DiffFile | null,
  newFile: null as DiffFile | null,
  diffContextLines: 10,
  diffStyle: 'split' as DiffStyle,
  comments: [] as CommentItem[],
  commitMessage: '',
  loadingSnapshot: false,
  loadingHistoryCommits: false,
  loadingHistoryFiles: false,
  loadingPatch: false,
  runningAction: '' as RunningAction,
  error: '',
})
